language: r
cache: packages
r: 3.5
pandoc_version: 2.2.1
repos:
  CRAN: https://cran.rstudio.com
notifications:
  email:
    on_failure: always
    on_success: never
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  _deploy.sh
